### ISSUE TITLE
multilanguage support ?

### ISSUE THREAD

**Issue by kiuKisas** [Ayowel/Ayowel.github.io#1]
Hello ! 
Tout d'abord bravo pour ce petit jeu intéractif super intéressant ! 
Je me disais que c'etais dommage qu'il n'y est qu'une version en français, as-tu pensé à faire une version en anglais ? 
Si tu as besoins d'aide, je peux aider ;)

**Comment by kiuKisas** [comment]
my bad -> [version anglaise](http://ncase.me/trust/)

**Comment by Ayowel** [comment]
Bonjour 😄 

En effet, le repo [trust](https://github.com/Ayowel/trust) était un fork qui a été détaché à ma demande ce matin même. Si tu as des corrections à faire dans la version française (ou anglaise), n'hésite pas à faire une PR ou à ouvrir une issue.

Merci d'y avoir joué et bonne continuation à toi
Ayowel
